---
title: "Zier_comparison_analysis"
author: "Emma"
date: "12/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(knitr)
library(kableExtra)
library(lubridate)
library(tableone)
library(forcats)
library(stringr)
library(janitor)
library(dplyr)
library(qwraps2)
library(plyr)
library(ggridges)
library(viridis)
library(RColorBrewer)
library(cowplot)
library(gridExtra)
library(data.table)
library(tibble)
options(qwraps2_markup = "markdown")
```

## Read in COPD data & Zier data
```{r read_data }

#TEAM COPD 
copd_data <- read_csv(here::here("Data", "20191021_Qualtrics data.csv"))
copd_codebook <- read_csv(here::here("Data", "20191014_Qualtrics codebook.csv"), skip = 1)

copd_codebook <- copd_codebook[, -1]
prefcols <- as.character(copd_codebook[1, ])
colnames(copd_data)<-prefcols
colnames(copd_codebook)<-prefcols
rm(prefcols)
copd_data <- copd_data[-2, ]
copd_data <- copd_data[-1, ]
rownames(copd_codebook)<-c("var", "description", "scoring") 

#----------------------
# TEAM ZIER 
zier_data <- read_csv(here::here("Data", "20191220_Zier Data.csv"))
zier_codebook <- read_csv(here::here("Data", "20191223_Zier codebook.csv"), skip = 1)

zier_codebook <- zier_codebook[, -1]
prefcols2 <- as.character(zier_codebook[1, ])
colnames(zier_data) <- prefcols2 
colnames(zier_codebook) <- prefcols2 
rm(prefcols2) 
rownames(zier_codebook) <- c("var", "description")

#---------------------
# Clean up 
rm(prefcols)
rm(prefcols2)

```

## Prep and subset COPD data for making figures :)
```{r subset_copd}

# Set up uid for the data 
a<-dim(copd_data)[1]

copd_data <- copd_data %>%
  mutate(uid=(1:a))

# Select the variables and order them from lowest survival to highest (zier_1 = highest)
zier_vars <- c("zier_1", "zier_2", "zier_3", "zier_4", "zier_5", "zier_6", "zier_7", "zier_8", "zier_9", "zier_10", "zier_11", "zier_12", "zier_13", "zier_14", "zier_15", "zier_16")
zier_vars <- rev(zier_vars)

# Gather the data 
copd_tbl <- copd_data %>% 
  dplyr::select(zier_vars) %>% 
  gather() %>% 
  mutate(key = factor(key, levels = zier_vars)) %>% 
  mutate(value = as.numeric(value)) %>% 
  filter(complete.cases(value))

# Clean up
rm(a)

```

## Read in Zier data 
```{r subset_zier }

zier_tbl <- zier_data %>% 
  dplyr::select(zier_vars) %>% 
  gather() %>% 
  mutate(key = factor(key, levels = zier_vars)) %>% 
  mutate(value = as.numeric(value)) %>% 
  filter(complete.cases(value))

```

# COPD & ZIER Ridge Plots
```{r ridge_plots}

# n for each statement
copd_counts <- copd_tbl %>% 
  filter(is.na(value) == FALSE) %>%
  group_by(key) %>% 
  tally()

zier_counts <- zier_tbl %>% 
  filter(is.na(value) == FALSE) %>%
  group_by(key) %>% 
  tally()

copd_counts
zier_counts

#-------------------------

# COPD ridge plot
copd_ridge <- copd_tbl %>% 
  
  ggplot(aes(x = value, y = key, fill = ..x.., vline_color = ..quantile..)) + 
  
  geom_density_ridges_gradient(bandwidth = 3, scale = 2, color = "white", 
                               quantile_lines = TRUE, vline_size = 1.25) + 
  
   scale_discrete_manual("vline_color", 
                        values = c("green", "red", "green", "white"), guide = "none") + 
  
  scale_discrete_manual("vlineTypes", 
                        values = c("dashed", "solid", "dashed", "dotted"), guide = "none") + 

  scale_x_continuous(limits = c(0, 100)) + 
  
  scale_fill_viridis(name = "Likelihood of survival", option = "C") + 
  
  labs(title = "COPD Population: Comparison of survival estimates between prognostic statements", 
       x = "Likelihood of survival (%)", 
       y = "Prognostic statement") + 
  scale_y_discrete(labels = c("He will definitely not survive. (n=58)", "He has a 5% chance of surviving. (n=53)", "It is unlikely he will survive. That means he will likely die. (n=57)", "It is very likely he will die. (n=54)", "It is very unlikely he will survive. (n=57)", "I don't think he will survive. (n=57)", "He probably will not survive. (n=58)", "It is possible he will not survive. (n=52)", "I am concerned he will not survive. (n=54)", "He has a 50% chance of surviving. (n=56)", "I am optimistic he will survive. (n=59)", "It is very unlikely he will die. (n=56)", "I think he will survive. (n=57)", "It is very likely he will survive. (n=57)", "He has a 90% chance of surviving. (n=62)", "He will definitely survive. (n=59)")) +
  
  theme_bw() 

copd_ridge

#-------------------------
# ZIER Ridge 
zier_ridge <- zier_tbl %>% 
  ggplot(aes(x = value, y = key, fill = ..x.., vline_color = ..quantile..)) + 
  geom_density_ridges_gradient(bandwidth = 3, scale = 2, color = "white", 
                               quantile_lines = TRUE, vline_size = 1.25) + 
  scale_discrete_manual("vline_color", 
                        values = c("pink", "red", "pink", "white"), guide = "none") + 
  scale_discrete_manual("vlineTypes", 
                        values = c("dashed", "solid", "dashed", "dotted"), guide = "none") + 
  scale_x_continuous(limits = c(0, 100)) + 
  scale_fill_viridis(name = "Likelihood of survival", option = "D") + 
  labs(title = "ZIER Population: Comparison of survival estimates between prognostic statements", 
       x = "Likelihood of survival (%)", 
       y = "Prognostic statement") +
  scale_y_discrete(labels = c("He will definitely not survive. (n=79)", "He has a 5% chance of surviving. (n=80)", "It is unlikely he will survive. That means he will likely die. (n=80)", "It is very likely he will die. (n=80)", "It is very unlikely he will survive. (n=80)", "I don't think he will survive. (n=80)", "He probably will not survive. (n=80)", "It is possible he will not survive. (n=80)", "I am concerned he will not survive. (n=80)", "He has a 50% chance of surviving. (n=80)", "I am optimistic he will survive. (n=80)", "It is very unlikely he will die. (n=80)", "I think he will survive. (n=78)", "It is very likely he will survive. (n=80)", "He has a 90% chance of surviving. (n=80)", "He will definitely survive. (n=80)")) + 
  theme_bw()

zier_ridge

```

# COPD & Zier Box Plots
```{r box_plots }

# COPD Boxplot
copd_box <- copd_tbl %>% 
  ggplot(aes(x = key, y = value)) + 
  geom_boxplot(fill = "orchid1") + 
  coord_flip() +
  scale_y_continuous(limits = c(0, 100)) + 
  labs(title = "Comparison of survival estimates between prognostic statements \n\n Outpatient Proxy Sample (Qualtrics COPD)", 
       y = "Likelihood of survival (%)", 
       x = "Prognostic statement") + 
  scale_x_discrete(labels = c("He will definitely not survive.", "He has a 5% chance of surviving.", "It is unlikely he will survive. That means he will likely die.", "It is very likely he will die.", "It is very unlikely he will survive.", "I don't think he will survive.", "He probably will not survive.", "It is possible he will not survive.", "I am concerned he will not survive.", "He has a 50% chance of surviving.", "I am optimistic he will survive.", "It is very unlikely he will die.", "I think he will survive.", "It is very likely he will survive.", "He has a 90% chance of surviving.", "He will definitely survive.")) + 
  theme_bw() + 
  stat_summary(fun.y=mean, geom="point", shape=4, size=3)

#--------------------------------
# Zier Boxplot
zier_box <- zier_tbl %>% 
  ggplot(aes(x = key, y = value)) + 
  geom_boxplot(fill = "aquamarine") + 
  coord_flip() +
  scale_y_continuous(limits = c(0, 100)) + 
  labs(title = "ICU Proxy Sample (Zier)", 
       y = "Likelihood of survival (%)", 
       x = "Prognostic statement") + 
  scale_x_discrete(labels = c("He will definitely not survive.", "He has a 5% chance of surviving.", "It is unlikely he will survive. That means he will likely die.", "It is very likely he will die.", "It is very unlikely he will survive.", "I don't think he will survive.", "He probably will not survive.", "It is possible he will not survive.", "I am concerned he will not survive.", "He has a 50% chance of surviving.", "I am optimistic he will survive.", "It is very unlikely he will die.", "I think he will survive.", "It is very likely he will survive.", "He has a 90% chance of surviving.", "He will definitely survive.")) + 
  theme_bw() + 
  stat_summary(fun.y=mean, geom="point", shape=4, size=3)


grid.arrange(copd_box, zier_box, nrow=2)

```

## Combined box plot :O 
```{r boxplot_combined}

# Make a combined copd-zier tbl 
copd_tbl <- copd_tbl %>% 
  mutate(group = "copd")
zier_tbl <- zier_tbl %>% 
  mutate(group = "zier")

combined_tbl <- rbind(copd_tbl, zier_tbl)

# Make boxplot 

cz_boxplot <- combined_tbl %>% 
  ggplot(aes(x = key, y = value, fill = group)) +
  geom_boxplot() + 
  coord_flip() +
  scale_y_continuous(limits = c(0, 108)) + 
  scale_fill_discrete(name = "Group", labels = c("Future ICU Surrogates", "Active ICU Surrogates"), guide=guide_legend(reverse=TRUE)) + 
  labs(title = "Surrogate Response to Prognostic Statements", 
       y = "Likelihood of survival (%)", 
       x = "Prognostic statement") + 
  scale_x_discrete(labels = c("He will definitely not survive.", "He has a 5% chance of surviving.", "It is unlikely he will survive. That means he will likely die.", "It is very likely he will die.", "It is very unlikely he will survive.", "I don't think he will survive.", "He probably will not survive.", "It is possible he will not survive.", "I am concerned he will not survive.", "He has a 50% chance of surviving.", "I am optimistic he will survive.", "It is very unlikely he will die.", "I think he will survive.", "It is very likely he will survive.", "He has a 90% chance of surviving.", "He will definitely survive.")) + 
  theme_bw() + 
  theme(legend.position = "bottom") +
  
  # Add summary stat mean 
  stat_summary(fun.y=mean, aes(group=group, shape="Average"), position=position_dodge(0.8), geom="point", shape=4, size=3) + 
  
  scale_shape_manual("Average", values=c("Mean"="X", "Median"="|")) + # why doesn't this show up? merp 
  
  annotate("text", x=16.2, y=107, label="n=80") +
  annotate("text", x=15.8, y=107, label="n=59") +
  annotate("text", x=15.2, y=107, label="n=80") +
  annotate("text", x=14.8, y=107, label="n=62") +
  annotate("text", x=14.2, y=107, label="n=80") +
  annotate("text", x=13.8, y=107, label="n=57") +
  annotate("text", x=13.2, y=107, label="n=78") +
  annotate("text", x=12.8, y=107, label="n=57") +
  annotate("text", x=12.2, y=107, label="n=80") +
  annotate("text", x=11.8, y=107, label="n=56") +
  annotate("text", x=11.2, y=107, label="n=80") +
  annotate("text", x=10.8, y=107, label="n=59") +
  annotate("text", x=10.2, y=107, label="n=80") +
  annotate("text", x=9.8, y=107, label="n=56") +
  annotate("text", x=9.2, y=107, label="n=80") +
  annotate("text", x=8.8, y=107, label="n=54") +
  annotate("text", x=8.2, y=107, label="n=80") +
  annotate("text", x=7.8, y=107, label="n=52") +
  annotate("text", x=7.2, y=107, label="n=80") +
  annotate("text", x=6.8, y=107, label="n=58") +
  annotate("text", x=6.2, y=107, label="n=80") +
  annotate("text", x=5.8, y=107, label="n=57") +
  annotate("text", x=5.2, y=107, label="n=80") +
  annotate("text", x=4.8, y=107, label="n=57") +
  annotate("text", x=4.2, y=107, label="n=80") +
  annotate("text", x=3.8, y=107, label="n=54") +
  annotate("text", x=3.2, y=107, label="n=80") +
  annotate("text", x=2.8, y=107, label="n=57") +
  annotate("text", x=2.2, y=107, label="n=80") +
  annotate("text", x=1.8, y=107, label="n=53") +
  annotate("text", x=1.2, y=107, label="n=80") +
  annotate("text", x=0.8, y=107, label="n=58") #+ 
  
  #annotation_custom("text", x="Averages n/ X = Mean n/ | = Median")
  

```


## Summary Statistics COPD
```{r summary_copd }

# COPD Summary statistics 
select <- grepl("zier", colnames(copd_data)) 
copd_data[,select] <- apply(copd_data[,select], 2, as.numeric)

tab_ridge_tbl <- copd_data %>% 
  dplyr::select(zier_vars)

sum <- summary.data.frame(tab_ridge_tbl)


select <- grepl("zier", colnames(zier_data)) 
zier_data[,select] <- apply(zier_data[,select], 2, as.numeric)

tab_ridge_tbl2 <- zier_data %>% 
  dplyr::select(zier_vars)

sum2 <- summary.data.frame(tab_ridge_tbl2)

rm(select)

```

## 2-sample Tests
```{r ks_wc_tests }

# Reorder variables from high to low survival (zier_1 = highest)
zier_vars <- c("zier_1", "zier_2", "zier_3", "zier_4", "zier_5", "zier_6", "zier_7", "zier_8", "zier_9", "zier_10", "zier_11", "zier_12", "zier_13", "zier_14", "zier_15", "zier_16")

#----------------------
# KS TEST 
# Part 1: The Function
ks_func <- function (zier_var) {
  zier_values <- dplyr::filter(zier_tbl, key == zier_var)[[2]]          # zier values for respective zier_var
  copd_values <- dplyr::filter(copd_tbl, key == zier_var)[[2]]          # copd values for respective zier_var
  
  ks.test(zier_values,copd_values)                                      # take a look: run ks test zier values against copd values
 
  zier_pop <- dplyr::filter(zier_tbl, key == zier_var)$value            # grab values of zier_tbl 
  copd_pop <- dplyr::filter(copd_tbl, key == zier_var)$value            # grab values of copd_tbl
  
  results <- ks.test(zier_pop,copd_pop)                                 # full set of ks.test results

  picky_results <- c("stat" = results$statistic, "p-val" = results$p.value) # pick the result that gets outputted  
}

# Part 2: Applying the function 
ks_results <- sapply(zier_vars, ks_func)           # iterate ks_func over all the zier_vars 

#----------------------
# WILCOX TEST 
wc_func <- function (zier_var) {
  zier_values <- dplyr::filter(zier_tbl, key == zier_var)[[2]]
  copd_values <- dplyr::filter(copd_tbl, key == zier_var)[[2]]
  
  wilcox.test(zier_values, copd_values)
  
  zier_pop <- dplyr::filter(zier_tbl, key == zier_var)$value 
  copd_pop <- dplyr::filter(copd_tbl, key == zier_var)$value 
  
  results <- wilcox.test(zier_pop, copd_pop) 
  
  picky_results <- c("stat" = results$statistic, "p-val" = results$p.value)
}

wc_results <- sapply(zier_vars, wc_func)


```



```{r median wilcoxon tests }

# Median response from future (COPD) icu surrogate group
copd_med <- apply(tab_ridge_tbl, 2, function(x) {
  median(x, na.rm=TRUE)
})

# Median response from future (COPD) with previous VENT experience
copd_data_vent <- filter(copd_data, scr_6 == "Yes")

copd_tbl_vent <- copd_data_vent %>% 
  dplyr::select(zier_vars) %>% 
  gather() %>% 
  mutate(key = factor(key, levels = zier_vars)) %>% 
  mutate(value = as.numeric(value)) %>% 
  filter(complete.cases(value))

copd_vent_med <- apply(tab_ridge_tbl3, 2, function(x) {
  median(x, na.rm=TRUE)
  })

copd_vent_med <- rev(copd_vent_med)

#rm(copd_data_vent)
#rm(copd_tbl_vent)

# Median response from active (zier) icu surrogate group
zier_med <- apply(tab_ridge_tbl2, 2, function(x) {
  median(x, na.rm=TRUE)
})

med_diff <- (zier_med) - (copd_med)

wc_med <- wilcox.test(zier_med, copd_med, paired=TRUE, conf.int=TRUE, exact=FALSE)

# Results: 
# Wilcoxon signed rank test with continuity correction

# data:  zier_med and copd_med
# V = 75.5, p-value = 0.004662
# alternative hypothesis: true location shift is not equal to 0
# 95 percent confidence interval:
#   6.250032 16.749942
# sample estimates:
# (pseudo)median 
#         11.156

mean()
#------------------------
# Sensitivity! 



```


```{r median wc sensitivity w vent }
# Data
copd_data_vent <- filter(copd_data, scr_6 == "Yes")

# Tbl 
select <- grepl("zier", colnames(copd_data_vent)) 
copd_data_vent[,select] <- apply(copd_data_vent[,select], 2, as.numeric)

tab_ridge_tbl3 <- copd_data_vent %>% 
  dplyr::select(zier_vars)

sum <- summary.data.frame(tab_ridge_tbl3)



# WC Test
copd_tbl_vent <- copd_data_vent %>% 
  dplyr::select(zier_vars) %>% 
  gather() %>% 
  mutate(key = factor(key, levels = zier_vars)) %>% 
  mutate(value = as.numeric(value)) %>% 
  filter(complete.cases(value))

copd_vent_med <- apply(tab_ridge_tbl3, 2, function(x) {
  median(x, na.rm=TRUE)
  })

copd_vent_med <- rev(copd_vent_med)
copd_vent_diff <- (zier_med) - (copd_vent_med)
  
wc_med_vent <- wilcox.test(zier_med, copd_vent_med, paired=TRUE, conf.int=TRUE, exact=FALSE)

# 	Wilcoxon signed rank test with continuity correction

# data:  zier_med and copd_vent_med
# V = 65, p-value = 0.005077
# alternative hypothesis: true location shift is not equal to 0
# 95 percent confidence interval:
#   7.249941 19.500009
# sample estimates:
# (pseudo)median 
#        12.4635 

  
```



